[package]
name = "smart_meter_receiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
thiserror = "1.0"
num_enum = "0.5.7"
hex = "0.4.3"
